In [ ]:
import numpy as np

# checking numpy version
print(np.__version__)

arr = np.array([10,20,30])

print(arr)
print(type(arr))


2.4.6
[10 20 30]
<class 'numpy.ndarray'>


NumPy - Ndarray Object



In [4]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr * 2)


[2 4 6 8]


In [5]:
# data type

print(arr.dtype)

int64


In [6]:
a = np.array([1,2,3], dtype=np.int32)
b = np.array([1,2,3], dtype=np.int64)

print(a.dtype)
print(b.dtype)

int32
int64


In [9]:
# Array Scalar Types

a = np.array([10,20,30])

print(a[1])

20


In [10]:
# Creating 1D array


arr1 = np.array([1,2,3])
print(arr1)

#  shape of array
print(arr1.shape)

[1 2 3]
(3,)


In [11]:
# 2D array

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.shape)

(2, 3)


In [ ]:
# 3D array

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr.shape)