In [ ]:
import numpy as np

arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element", arr_2D[1,2])
print("Entire row: ", arr_2D[1])
print("Enter column: ",arr_2D[:, 1]) # targeting the column

Specific element 6
Entire row:  [4 5 6]
Enter column:  [2 5 8]


Sorting

In [3]:
unsorted_arr = np.array([3,2,1,4,6,5])
print("sorted array: ", np.sort(unsorted_arr))


sorted array:  [1 2 3 4 5 6]


In [6]:
array_2d_unsorted = np.array([[2,13,4], [1,8,5], [3,7,6]])

print("sorted 2D array by column", np.sort(array_2d_unsorted, axis=1))

sorted 2D array by column [[ 2  4 13]
 [ 1  5  8]
 [ 3  6  7]]


### Filter

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("even_numbers", even_number)

even_numbers [ 2  4  6  8 10]


### Filter with mask

In [ ]:
mask = numbers > 5 # adding the expression
print("numbers greater than 5: ", numbers[mask])

numbers greater than 5:  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [ ]:
# passing the indices
indices = [0, 1, 4]
print(numbers[indices])

# using where clause 
where_result = np.where(numbers > 5)
print(where_result) #it stores the indexs
print("NP where", numbers[where_result])

[1 2 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [13]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# gets added to the value
combined_array = arr1 + arr2 
print(combined_array)

combined_arrays = np.concatenate((arr1,arr2))
print("combined_arrays: ", combined_arrays)

[5 7 9]
combined_arrays:  [1 2 3 4 5 6]


### array compatibilty

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatibility shapes: ", a.shape == b.shape == c.shape)


compatibility shapes:  True


In [23]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

# vstack -> add rows (vertical stack)
with_new_row = np.vstack((original, new_row))
print(original)
# print("with_new_row \n", with_new_row)


# hstack -> add columns (horizontal stack)
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
with new column [[1 2 7]
 [3 4 8]]


### Delete operation

In [24]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print('deleted array: ', deleted)

deleted array:  [1 2 4 5]
